### ISSUE TITLE
How to enable wireless charging and usb otg at the same time

### ISSUE THREAD

**Issue by ercintorun** [Oebbler/elite-boeffla-kernel-lineage14.1-i9300#1]
Hello Oebbler, 

I'm compiling your kernel for galaxy s3 i9300 and succesfully added a driver for my need (trying to manage a 3d printer). I need to enable wireless charging with usb otg at the same time. 
I use a usb cable with 5vpin cut out to manage the printer. Could not find the right kernel settings, could you help ?

**Comment by Oebbler** [comment]
Hello ercitorun,

If you customize my source code, I can not give you any support for this because I don't know what exactly you have done.
By now, I haven't recognized any issues with charging and USB-OTG.

Best regards,
Oebbler
